export default {
  //LOGIN
  LOGIN_USER_REQUEST: "LOGIN_USER_REQUEST",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_FAILURE: "LOGIN_USER_FAILURE",
  //GetCartList
  GET_CART_LIST_REQUEST: "GET_CART_LIST_REQUEST",
  GET_CART_LIST_SUCCESS: "GET_CART_LIST_SUCCESS",
  GET_CART_LIST_FAILURE: "GET_CART_LIST_FAILURE",
  //GetAllOrders
  GET_ALL_ORDER_LIST_REQUEST: "GET_ALL_ORDER_LIST_REQUEST",
  GET_ALL_ORDER_LIST_SUCCESS: "GET_ALL_ORDER_LIST_SUCCESS",
  GET_ALL_ORDER_LIST_FAILURE: "GET_ALL_ORDER_LIST_FAILURE",
  //get Favorite
  GET_FAVORITE_REQUEST: 'GET_FAVORITE_REQUEST',
  GET_FAVORITE_SUCCESS: 'GET_FAVORITE_SUCCESS',
  GET_FAVORITE_FAILURE: 'GET_FAVORITE_FAILURE',
  //get Flash Sales
  GET_FLASH_SALES_REQUEST: 'GET_FLASH_SALES_REQUEST',
  GET_FLASH_SALES_SUCCESS: 'GET_FLASH_SALES_SUCCESS',
  GET_FLASH_SALES_FAILURE: 'GET_FLASH_SALES_FAILURE',
  //get Best Salling Products
  GET_BEST_SELLING_PRODUCTS_REQUEST: 'GET_BEST_SELLING_PRODUCTS_REQUEST',
  GET_BEST_SELLING_PRODUCTS_SUCCESS: 'GET_BEST_SELLING_PRODUCTS_SUCCESS',
  GET_BEST_SELLING_PRODUCTS_FAILURE: 'GET_BEST_SELLING_PRODUCTS_FAILURE',
  //get profile
  GET_PROFILE_REQUEST: "GET_PROFILE_REQUEST",
  GET_PROFILE_SUCCESS: "GET_PROFILE_SUCCESS",
  GET_PROFILE_FAILURE: "GET_PROFILE_FAILURE",
  //logout
  LOGIN_LOGOUT_REQUEST: "LOGIN_LOGOUT_REQUEST",
  LOGIN_LOGOUT_SUCCESS: "LOGIN_LOGOUT_SUCCESS",
  //IsloggedIn
  CHECK_LOGIN_REQUEST: "CHECK_LOGIN_REQUEST",
  CHECK_LOGIN_SUCCESS: "CHECK_LOGIN_SUCCESS",

};
